image:
  repository: 225187407954.dkr.ecr.us-east-1.amazonaws.com/gitops-app
  tag: "ecf924e3304d6b5c3d018d3f66e8f1603006f91f"
  pullPolicy: Always

replicaCount: 2

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
